config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum:12}
    validates :description, presence: true, length: {minimum:10, maximum:50}
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: { maximum:3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destory]
    def show
         
    end

    def index 
        @articles = Article.all
    end

    def create 
        @articles = Article.new(article_params)
        if @articles.save
            flash[:notice] = "Article was created Sucessfully."
            redirect_to @articles
        else 
            render 'new'
        end
    end

    def new 
        @articles = Article.new
    end

    def update 
        if @articles.update(article_params)
            flash[:notice] = "Article was updated sucessfully"
            redirect_to @articles
        else
            render 'edit'
        end
    end

    def edit 
    end

    def destroy 
        @articles.destroy
        redirect_to articles_path
    end

    private

    def set_article 
        @articles = Article.find(params[:id])
    end

    def article_params 
        params.require(:article).permit(:title,:description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
        render html: 'Hello'
    end

    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @articles.errors.any? %>
    <h2>The following errors prevented the article from update</h2>
    <ul>
        <%@articles.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @articles,local: true) do |f|%>
    <p>
        <%=f.label :title%><br/>
        <%=f.text_field :title%>
    </p>

    <p>
        <%= f.label :description%><br/>
        <%= f.text_area :description%>
    </p>

    <p>
        <%=f.submit%>
    </p>
<%end%>

app/views/articles/edit.html.erb
<h1>Update article</h1>

<%= render 'form'%>

<%= link_to 'Cancel and return', articles_path%>

app/views/articles/index.html.erb
<h1>List of Articles</h1>


<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>


    <tbody>
        
        <% @articles.each do |article| %>
        <tr>
            <td><%=article.title%></td>
            <td><%=article.description%></td>
            <td><%= link_to 'Show', article_path(article)%></td>
            <td><%= link_to 'Edit', edit_article_path(article)%></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete%></td>
        </tr>   
        <% end %> 
    </tbody>

</table>

<p>
    <%= link_to 'Create New Article', new_article_path%>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form'%>

<%= link_to 'Return to articles', articles_path%>

app/views/articles/show.html.erb
<h1>Showing Articles</h1>

<p><strong>Title:</strong><%=@articles.title %></p>
<p><strong>Description:</strong><%=@articles.description %></p>

<%= link_to 'Edit', edit_article_path(@articles)%> |
<%= link_to 'Delete', article_path(@articles),method: :delete, data:{confirm: "Arey you sure"}%> |
<%= link_to 'Return to articles listing', articles_path%>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
    <%= msg%>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticalBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
     <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>